# Generated by Django 2.2.4 on 2021-04-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='under_30',
            new_name='granted',
        ),
    ]
