# Generated by Django 2.2.4 on 2021-04-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_auto_20210429_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_wish', to='exam_app.User'),
        ),
    ]
